---
- hosts: tag_Name_master
  user: ubuntu
  gather_facts: True
  become: yes
  become_method: sudo
  tasks:
    - name: master_ip
      set_fact:
        master: "{{ hostvars[inventory_hostname]['groups']['tag_Name_master'] | to_json }}"
    - name: master
      shell: /home/ubuntu/splunk/bin/splunk edit cluster-config -mode master -replication_factor 3 -search_factor 2 -secret 66546654 -auth admin:66546654 ; /home/ubuntu/splunk/bin/splunk restart ;

- hosts: tag_Name_indexer*
  user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: master_ip
      set_fact:
        master: "{{ hostvars[inventory_hostname]['groups']['tag_Name_master'] | to_json }}"
    - name: Indexer
      shell: /home/ubuntu/splunk/bin/splunk edit cluster-config -mode slave -master_uri https://"{{master}}":8089 -replication_port 4598 -secret 66546654 -auth admin:66546654 ; /home/ubuntu/splunk/bin/splunk restart ;
  gather_facts: True

- hosts: tag_Name_search*
  user: ubuntu
  gather_facts: True
  become: yes
  become_method: sudo
  tasks:
    - name: master_ip
      set_fact:
        master: "{{ hostvars[inventory_hostname]['groups']['tag_Name_master'] | to_json }}"
    - name: Search Head
      shell: /home/ubuntu/splunk/bin/splunk edit cluster-config -mode searchhead -master_uri https://"{{master}}":8089 -secret 66546654 -auth admin:66546654 ; /home/ubuntu/splunk/bin/splunk restart ;

